### ISSUE TITLE
Incorrect alpha blending when drawing an image with an alpha channel over another image

### ISSUE THREAD

**Issue by Marlamin** [mono/libgdiplus#372]
libgdiplus version: 4.2-1+b1 (Debian stable) and the version shipped in [this](https://www.nuget.org/packages/runtime.linux-x64.CoreCompat.System.Drawing/1.0.0-beta009) (unable to tell). 

I'm not easily able to compile master so apologies if this is already resolved. 

I'm working on an application that compiles game maps out of several textures that heavily use alpha blending, it is using .NET Core's System.Drawing.Common which relies on libgdiplus (either the one on system or shipped with the application through the earlier linked NuGet package). The issue happens when I use Graphics.DrawImage to draw an image heavily utilizing the alpha channel over another image. The output appears pretty distorted wherever the alpha channel is used. 

I have set up a repo with sample images/code [**here**](https://github.com/Marlamin/AlphaBlendingRepro) that I also used to generate the following images (I cropped them for the issues sake, though). 

Expected output (generated on Windows):
![image](https://user-images.githubusercontent.com/50212/39098803-89bc000a-4670-11e8-80d6-9f8c6b5534cd.png)

Actual output (generated on my Debian machine): 
![image](https://user-images.githubusercontent.com/50212/39098800-83429806-4670-11e8-9a61-e29de40abb26.png)

If anyone is willing to test the application with master, that would be great. If it is already fixed or a case of PEBKAC, my apologies. If it is not I'm happy to help test any solutions.

**Comment by filipnavara** [comment]
Thanks for the report. I will look into it shortly. It seems to be issue with handling ARGB images (as opposed to PARGB, which is premultiplied).

**Comment by Marlamin** [comment]
Set up a new VM on my PC to compile the branch with the fix. Result is MUCH improved (no more distortion etc, yay) but not entirely the same yet (there's still a sort of dark border compared to the Windows version). 

![image](https://user-images.githubusercontent.com/50212/39129580-24f2aab6-470b-11e8-9857-647e163f5f4c.png)

I've updated the repro repo sample images with an actual map background/layer for better visibility of the issue, border stands out instead of merging with the terrain.

![image](https://user-images.githubusercontent.com/50212/39131896-dc651602-4710-11e8-8627-d1ae315ffd20.png)

Interestingly enough, I still have [this issue](https://pbs.twimg.com/media/DbZ5cL3WAAAyFSp.png:large) (which I guess is a separate one) with the full fledged non-repro application (which reads decompressed textures instead of on-disk images). I guess there's a difference between the image data in memory and when reading from an image written to disk... unsure where that issue is exactly but I wouldn't be surprised if it is on my end. I'll investigate more to see if that issue is libgdiplus or not. If not I can easily get around it by writing stuff to disk first (after above is fixed). 😄

**Comment by filipnavara** [comment]
I found a couple more bugs in the code and fixed them in the pull request. It may help with the other issue.

**Comment by Marlamin** [comment]
Looks like the other issue is fixed now! Awesome! Hoping to see this in master soon :)

![image](https://user-images.githubusercontent.com/50212/42943779-057c361e-8b64-11e8-936a-b548d7f77070.png)

**Comment by filipnavara** [comment]
Fix is merged.

**Comment by Marlamin** [comment]
Awesome, I'll compile it manually for now and then switch over to the one in Ubuntu repo when that updates. The issue that repro code is reproducing is still a thing (my main app is fine now though), should this issue remain open for that?
